version: "3"

services:

  go:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      GOOS: linux
    env_file:
      - ./aws.env
    volumes:
      - ./:/src
    working_dir: /src
    command: ["bash"]

  fpm:
    build:
      context: ./docker/fpm
      dockerfile: Dockerfile
    volumes:
      - ./docker/fpm:/data
      - ./:/src
    working_dir: /data
    env_file:
      - fpm.env
    command: ["/data/run-fpm.sh"]
